version: '3'

services:
  db:
    image: postgres
    container_name: jm_database
    ports:
      - "5432:5432"
    volumes:
      - db_jumping_minds:/var/lib/postgresql/data
    env_file:
      - ./config/dev.env
    networks: 
      - db_network

  pgadmin:
    image: dpage/pgadmin4:6.7
    container_name: jm_admin
    links:
      - db
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@jm.com
      PGADMIN_DEFAULT_PASSWORD: delhi
    ports:
      - "80:80"
    volumes:
      - pg_admin_jumping_minds:/var/lib/pgadmin
    networks: 
      - db_network

  redis:
    image: redis:latest
    container_name: jm_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_jumping_minds_v1:/data
    restart: always
    networks: 
      - redis_network

networks:
  db_network:
    driver: bridge
  redis_network:
    driver: bridge

volumes:
  db_jumping_minds:
  pg_admin_jumping_minds:
  redis_jumping_minds_v1:
