# Generated by Django 4.2.3 on 2023-07-26 14:25

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Elevator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=256, null=True)),
                ("current_floor", models.IntegerField(default=0)),
                (
                    "traverse_floors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("close", models.BooleanField(default=True)),
                ("up", models.BooleanField(null=True)),
                ("operational", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Elevator",
                "verbose_name_plural": "Elevators",
                "db_table": "elevator",
            },
        ),
        migrations.CreateModel(
            name="ElevatorRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_floor", models.IntegerField()),
                ("to_floor", models.IntegerField()),
                (
                    "elevator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elevator.elevator",
                    ),
                ),
            ],
            options={
                "verbose_name": "ElevatorRequest",
                "verbose_name_plural": "Elevator Requests",
                "db_table": "elevator_request",
            },
        ),
    ]
